name: Docker Image CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  release:
    types: [ "published" ]
  workflow_dispatch: {}

env:
  PUSH_IMAGE: ${{ startsWith(github.ref, 'refs/tags/') }}
  IMAGE_VERSION: ${{ github.event_name == 'release' && github.ref_name || format('-{0}.{1}', (github.event_name == 'pull_request' && 'pr' || github.ref_name), github.run_number) }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        release: [bullseye, bookworm]
        include:
          - is_primary: false
          - release: bookworm
            is_primary: true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      MATRIX_TAG: ${{ format('{0}', matrix.release) }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push the Image
      uses: docker/build-push-action@v6
      with:
        context: '.'
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        build-args: |
          OS_RELEASE=${{ matrix.release }}
        #push: ${{ env.PUSH_IMAGE }}
        tags: |
          ${{ matrix.is_primary && github.repository || '' }}
          ${{ format('{0}:{1}', github.repository, matrix.release) }}
          ${{ format('{0}:{1}-{2}', github.repository, matrix.release, env.IMAGE_VERSION) }}
